### ISSUE TITLE
Phd Thesis Linnhoff

### ISSUE THREAD

**Issue by jdsika** [openMSL/sl-1-5-sensor-model-testing#16]
Please add the missing new publications.

**Comment by jdsika** [comment]
Add new category of publications for model building

**Comment by PhRosenberger** [comment]
Such a collection of publications focussing on model development is already available: https://github.com/openMSL/sl-1-5-sensor-model-testing/blob/main/doc/collection.md

------------------------------------------------------------
However, we can discuss, if and how we collect measurement campaigns and scenarios for model calibration and validation inside of such model development publications.

I would propose to point to such calibration- and validation-specific chapters inside of them like:
- Chapters 4.2 (Experiments), 5.2 (Experiments) and 6.2-6.4 (Model Calibration) from [Dissertation Linnhoff](https://tuprints.ulb.tu-darmstadt.de/23116/1/Dissertation_Linnhoff_20230120.pdf)
- Chapter 5 from [Dissertation Holder](https://tuprints.ulb.tu-darmstadt.de/17545/1/Dissertation_Martin_Holder_2021.pdf)

@jdsika what do you think?

**Comment by jdsika** [comment]
I like!
