### ISSUE TITLE
Tracefile Writer FMU

### ISSUE THREAD

**Issue by jdsika** [openMSL/sl-1-5-sensor-model-testing#23]
I would like to configure the "Tracefile FMU" to use it either as Reader or as Writer FMU in order to store the .osi tracefiles. We want to strenghten the usage of the tracefile format and we may evaluate the files in a second processing step without the use of a co-simulation and FMUs. (e.g. Python scripts)

**Comment by ClemensLinnhoff** [comment]
I agree, I already had this in my mind as one of the next steps for the pipeline. But I would rather create the tracefile output as a separate FMU. The basic code for tracefile generation is already part of some models (see e.g. [here](https://github.com/openMSL/sl-1-2-reflection-based-lidar-object-model/tree/main/src/model/strategies/binary-sensordata-output-strategy)). I would just put the code into a separate FMU, so every model can use it.

And then the integration test action, that currently already scans the test folders for ssd files and automatically builds the test pipeline, can also scan for .py files and execute them after the tracefile was generated. Then the test is done directly in the pipeline, and the tracefile can also be stored as an Artifact, so it can additionally be downloaded and used later.

**Comment by ClemensLinnhoff** [comment]
Work on a trace file writer FMU is now ongoing here: https://gitlab.com/persival-open-source/open-simulation-interface/osi-sensordata-trace-file-writer/-/merge_requests/1

Once tested and merged into the main branch, the trace file player will be incorporated into the credibility assessment workflow.
