### ISSUE TITLE
Tracefile Player location

### ISSUE THREAD

**Issue by jdsika** [openMSL/sl-1-5-sensor-model-testing#31]
Hi @ClemensLinnhoff I noticed that the tracefile player and the writer are on different locations (GitLab and GitHub). Will you move the more visible open source components to GitHub overall and make a public archive out of the GitLab repo?

Best regards
Carlo

**Comment by ClemensLinnhoff** [comment]
I think a better idea in the long run would be to have a tooling sub-library in openMSL. Then there would be a common place for smaller tools like trace file players, trace file writers, visualizers, data converters, bridges (e.g. to ROS) etc.
