### ISSUE TITLE
Move test tools to new tooling sub-library

### ISSUE THREAD

**Issue by ClemensLinnhoff** [openMSL/sl-1-5-sensor-model-testing#36]
The test tools in this repository can not only be used for sensor model testing, but for all OSMP models. Therefore, they should be moved to a separate tooling sub-library.

This is also connected to #31.

**Comment by ClemensLinnhoff** [comment]
@jdsika How should we proceed with this issue? Should I already move the test tools to a tooling sub-library? Because in accordance with the governance rules, a new sub-library can only be opened, if there are at least 3 maintainers.

**Comment by jdsika** [comment]
I talked to @afwalser today. We will organize a special day for interested companies explaining OpenMSL and announce it through the official channels. For this event I will present the current state and we can prepare "suggestions" for new libraries:
Scenario SL
Environmental Model SL
Traffic Participant SL
Tooling SL

We can create the names in the main readme and stating it is in initialization phase and give an abstract and also a suggestion for a repository.

It is basically a call for participants with a vivid example of what we are actually searching for
